/** Shared form placeholders, limits, and dropdown options. */

export const FORM_LIMITS = {
  text: 100,
  name: 50,
  email: 100,
  phone: 10,
  password: 128,
  employeeCode: 32,
  vehicleNumber: 15,
  licenseNumber: 25,
  postalCode: 6,
  textarea: 500,
  url: 2048,
} as const;

export const PLACEHOLDERS = {
  name: 'Example: John Doe',
  firstName: 'Example: John',
  lastName: 'Example: Doe',
  email: 'Example: john@example.com',
  phone: 'Example: 9876543210',
  password: 'Minimum 8 characters',
  employeeCode: 'Example: EMP-1001',
  vehicleNumber: 'Example: GJ05AB1234',
  vehicleId: 'Example: VH-1001',
  licenseNumber: 'Example: DL0420110149646',
  city: 'Example: Ahmedabad',
  postalCode: 'Example: 395006',
  tripId: 'Example: TR-2001 (optional)',
  driverId: 'Example: DR-3001 (optional)',
  fuelStation: 'Example: Shell Highway Station',
  fuelQuantity: 'Example: 45',
  cost: 'Example: 4500',
  amount: 'Example: 1500',
  weight: 'Example: 500',
  distance: 'Example: 250',
  odometer: 'Example: 45230',
  cargoName: 'Example: Industrial Equipment',
  source: 'Example: Ahmedabad, Gujarat',
  destination: 'Example: Mumbai, Maharashtra',
  title: 'Example: Highway Toll - NH48',
  vendorName: 'Example: AutoCare Service Center',
  serviceCenter: 'Example: Main Workshop, Sector 5',
  receiptUrl: 'Example: https://receipts.example.com/file.pdf',
  photoUrl: 'Example: https://images.example.com/photo.jpg',
  search: 'Search by name, vehicle, driver…',
  searchUsers: 'Search users by name or email…',
  orgName: 'Example: TransitOps Fleet Co.',
  timezone: 'Example: Asia/Kolkata',
  notes: 'Add optional notes (max 500 characters)',
  cancelReason: 'Example: Customer cancelled the shipment',
} as const;

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const;

export const COUNTRIES = ['India', 'United States', 'United Kingdom', 'Canada', 'Australia'] as const;

export const BLOOD_GROUP_OPTIONS = [
  { value: 'A+', label: 'A+' },
  { value: 'A-', label: 'A-' },
  { value: 'B+', label: 'B+' },
  { value: 'B-', label: 'B-' },
  { value: 'AB+', label: 'AB+' },
  { value: 'AB-', label: 'AB-' },
  { value: 'O+', label: 'O+' },
  { value: 'O-', label: 'O-' },
] as const;

export const DEFAULT_FORM_OPTIONS = {
  mode: 'onBlur' as const,
  reValidateMode: 'onChange' as const,
};

export const FILE_UPLOAD = {
  maxSizeBytes: 10 * 1024 * 1024,
  accept: 'image/jpeg,image/png,image/gif,image/webp,application/pdf,.jpg,.jpeg,.png,.gif,.webp,.pdf',
  acceptLabel: 'Images and PDF (max 10 MB each)',
} as const;
